/**
 * adsHandlers.js
 * Deterministic command handlers for Ads Agent and AdCampaign lifecycle.
 */

const AdsAgent = require("../../agents/AdsAgent");
const AdCampaign = require("../../../models/AdCampaign");
const WorkApproval = require("../../../models/WorkApproval");
const CreativeAgent = require("../../agents/CreativeAgent");
const auditService = require("../../execution/auditService");

/**
 * Creates a new AdCampaign draft and blueprint
 */
exports.createCampaign = async (params, ctx = {}) => {
  const customerId = params.customerId || ctx.customerId;
  if (!customerId) {
    throw new Error("Customer ID is required to create an Ad Campaign.");
  }

  const userId = ctx.userId || ctx.user?._id;
  const blueprint = await AdsAgent.generateCampaignPlan({
    customerId,
    locationId: params.locationId || ctx.locationId || null,
    parameters: params,
    userId,
  });

  let rawConversion = String(params.conversionType || blueprint.conversionType || "INSTANT_FORM").toUpperCase();
  let normalizedConversion = "INSTANT_FORM";
  if (rawConversion.includes("WHATSAPP")) normalizedConversion = "WHATSAPP";
  else if (rawConversion.includes("CALL")) normalizedConversion = "PHONE_CALL";
  else if (rawConversion.includes("LANDING") || rawConversion.includes("PAGE") || rawConversion.includes("WEBSITE")) normalizedConversion = "LANDING_PAGE";

  let rawObjective = String(params.objective || blueprint.objective || "LEAD_GENERATION").toUpperCase();
  let normalizedObjective = "LEAD_GENERATION";
  if (rawObjective.includes("WHATSAPP")) normalizedObjective = "WHATSAPP_MESSAGES";
  else if (rawObjective.includes("CALL")) normalizedObjective = "CALLS";
  else if (rawObjective.includes("TRAFFIC") || rawObjective.includes("WEBSITE")) normalizedObjective = "WEBSITE_TRAFFIC";
  else if (rawObjective.includes("AWARENESS") || rawObjective.includes("REACH")) normalizedObjective = "AWARENESS";

  // Upsert or Save Draft AdCampaign
  let campaignDoc = await AdCampaign.findOne({ campaignId: blueprint.campaignId });
  if (!campaignDoc) {
    campaignDoc = new AdCampaign({
      campaignId: blueprint.campaignId,
      customerId: blueprint.customerId,
      clientLocationId: blueprint.locationId || null,
      campaignName: blueprint.campaignName,
      platform: blueprint.platform,
      objective: normalizedObjective,
      conversionType: normalizedConversion,
      budget: blueprint.budget,
      duration: {
        startDate: new Date(),
        days: blueprint.budget.days || 10,
      },
      targetLocations: blueprint.audiences[0]?.locations || [],
      promotedServices: params.promotedServices || [],
      promotedOffer: params.offerDetails || "Special Offer",
      strategy: blueprint.strategy,
      audiences: blueprint.audiences,
      adVariants: blueprint.adVariants,
      creativeRequirements: blueprint.creativeRequirements,
      qaAudit: blueprint.qaAudit,
      status: "Pending Approval",
      version: 1,
      versionHistory: [
        {
          version: 1,
          snapshot: blueprint,
          revisionNote: "Initial Campaign Blueprint generated by AI Ads Agent",
          modifiedBy: userId || null,
          modifiedAt: new Date(),
        },
      ],
      createdBy: userId || blueprint.customerId,
    });
    await campaignDoc.save();

    // Create WorkApproval ticket
    const approval = new WorkApproval({
      approvalType: "AdCampaign",
      adCampaignId: campaignDoc._id,
      customer: blueprint.customerId,
      submittedBy: userId || blueprint.customerId,
      reviewMessage: `Ad Campaign Blueprint: ${blueprint.campaignName} (₹${blueprint.budget.amount}/day, ${blueprint.budget.days} days)`,
      status: "Pending Approval",
    });
    await approval.save();

    campaignDoc.approvalId = approval._id;
    await campaignDoc.save();
  }

  return {
    campaignId: campaignDoc.campaignId,
    adCampaignDbId: campaignDoc._id,
    campaignName: campaignDoc.campaignName,
    platform: campaignDoc.platform,
    objective: campaignDoc.objective,
    conversionType: campaignDoc.conversionType,
    budget: campaignDoc.budget,
    audiences: campaignDoc.audiences,
    adVariants: campaignDoc.adVariants,
    creativeRequirements: campaignDoc.creativeRequirements,
    qaAudit: campaignDoc.qaAudit,
    status: campaignDoc.status,
    version: campaignDoc.version,
    blueprint,
  };
};

/**
 * Revises an existing AdCampaign draft (e.g. modify budget, audiences, or creatives)
 */
exports.reviseCampaign = async (params, ctx = {}) => {
  const { campaignId, revisionInstruction, updatedBudget, updatedAudiences, updatedCreativeFormats } = params;
  if (!campaignId) {
    throw new Error("Campaign ID is required for revision.");
  }

  const campaign = await AdCampaign.findOne({ campaignId });
  if (!campaign) {
    throw new Error(`AdCampaign not found with ID: ${campaignId}`);
  }

  const userId = ctx.userId || ctx.user?._id;

  // Apply updates
  if (updatedBudget && !isNaN(Number(updatedBudget)) && Number(updatedBudget) > 0) {
    campaign.budget.amount = Number(updatedBudget);
    campaign.budget.totalBudget = campaign.budget.amount * (campaign.duration.days || 10);
  }

  if (updatedAudiences && Array.isArray(updatedAudiences)) {
    campaign.audiences = updatedAudiences;
  }

  if (updatedCreativeFormats && Array.isArray(updatedCreativeFormats)) {
    // Regenerate creative requirements for new formats
    const newReqs = [];
    if (updatedCreativeFormats.some((f) => f.includes("Poster") || f.includes("Banner"))) {
      newReqs.push({
        requirementId: `req_poster_${Date.now()}`,
        format: "Poster / Banner",
        aspectRatio: "1:1",
        concept: `${campaign.campaignName} Banner`,
        headline: campaign.adVariants[0]?.headline || "Transform Your Look",
        status: "Pending Generation",
      });
    }
    if (updatedCreativeFormats.some((f) => f.includes("Reel") || f.includes("Story") || f.includes("Video"))) {
      newReqs.push({
        requirementId: `req_reel_${Date.now()}`,
        format: "Reel / Story",
        aspectRatio: "9:16",
        concept: `${campaign.campaignName} Video Reel`,
        headline: campaign.adVariants[1]?.headline || "Top-Rated Service",
        status: "Pending Generation",
      });
    }
    if (newReqs.length > 0) campaign.creativeRequirements = newReqs;
  }

  // Increment version
  const newVersion = campaign.version + 1;
  campaign.version = newVersion;
  campaign.versionHistory.push({
    version: newVersion,
    snapshot: campaign.toObject(),
    revisionNote: revisionInstruction || "Campaign parameters revised",
    modifiedBy: userId || null,
    modifiedAt: new Date(),
  });

  await campaign.save();

  return {
    success: true,
    campaignId: campaign.campaignId,
    version: campaign.version,
    budget: campaign.budget,
    creativeRequirements: campaign.creativeRequirements,
    status: campaign.status,
    message: `Ad Campaign revised to Version ${newVersion}.`,
  };
};

/**
 * Approves an AdCampaign draft and triggers Creative Agent handoff
 */
exports.approveCampaign = async (params, ctx = {}) => {
  const { campaignId } = params;
  if (!campaignId) {
    throw new Error("Campaign ID is required for approval.");
  }

  const campaign = await AdCampaign.findOne({ campaignId });
  if (!campaign) {
    throw new Error(`AdCampaign not found with ID: ${campaignId}`);
  }

  const userId = ctx.userId || ctx.user?._id;
  campaign.status = "Approved";

  // Update WorkApproval ticket if linked
  if (campaign.approvalId) {
    await WorkApproval.findByIdAndUpdate(campaign.approvalId, {
      status: "Approved",
      approvedBy: userId || null,
      approvedAt: new Date(),
    });
  }

  await campaign.save();

  // 1. Pillar 1: Auto-Creative Handoff (Spawns Work deliverables and concept links)
  let handoffSummary = null;
  try {
    const adCreativeHandoffService = require("../../../services/adCreativeHandoffService");
    handoffSummary = await adCreativeHandoffService.provisionCampaignCreatives(campaign, userId);
  } catch (handoffErr) {
    console.warn("[AdsHandler] Creative handoff warning:", handoffErr.message);
  }

  // 2. Pillar 2: Meta Marketing API Auto-Dispatch (if requested or auto-launch enabled)
  let dispatchSummary = null;
  if (params.autoDispatch !== false) {
    try {
      const metaAdsDispatchService = require("../../../services/metaAdsDispatchService");
      dispatchSummary = await metaAdsDispatchService.dispatchCampaign(campaign);
    } catch (dispatchErr) {
      console.warn("[AdsHandler] Auto-dispatch note:", dispatchErr.message);
    }
  }

  return {
    success: true,
    campaignId: campaign.campaignId || campaign._id,
    campaignName: campaign.campaignName,
    platform: campaign.platform,
    objective: campaign.objective,
    budget: campaign.budget,
    status: dispatchSummary?.status || "Approved",
    creativeRequirements: campaign.creativeRequirements,
    creativesProvisioned: handoffSummary?.creativesProvisioned || 0,
    generatedAssets: handoffSummary?.generatedAssets || campaign.generatedAssets || null,
    dispatchSummary,
    message: `Ad Campaign approved and deployed! 1:1 Promotional Poster and 30s Reel Script generated and queued in CRM Work ledger.`,
  };
};

/**
 * Audience Recommendation Only
 */
exports.recommendAudience = async (params, ctx = {}) => {
  const customerId = params.customerId || ctx.customerId;
  const Customer = require("../../../models/Customer");
  const customer = await Customer.findById(customerId).lean();
  const planner = require("../../agents/ads/AudiencePlanner");
  const audiences = planner.generateAudiences({ customer, parameters: params });
  return { audiences };
};

/**
 * Budget Recommendation Only
 */
exports.recommendBudget = async (params, ctx = {}) => {
  const customerId = params.customerId || ctx.customerId;
  const Customer = require("../../../models/Customer");
  const customer = await Customer.findById(customerId).lean();
  const calculator = require("../../agents/ads/BudgetCalculator");
  const budget = calculator.calculateBudget({ customer, parameters: params });
  return { budget };
};

/**
 * Strategy Creation Only
 */
exports.createStrategy = async (params, ctx = {}) => {
  const customerId = params.customerId || ctx.customerId;
  const Customer = require("../../../models/Customer");
  const customer = await Customer.findById(customerId).lean();
  const engine = require("../../agents/ads/AdsStrategyEngine");
  const strategy = engine.generateStrategy({ customer, parameters: params });
  return { strategy };
};
