/**
 * conversationStateMachine.js
 * State machine for the Digitalness AI Workspace Conversational Engine.
 */

const WORKSPACE_STATES = {
  IDLE: "IDLE",
  UNDERSTANDING: "UNDERSTANDING",
  AWAITING_ENTITY: "AWAITING_ENTITY",
  COLLECTING_INPUT: "COLLECTING_INPUT",
  AWAITING_APPROVAL: "AWAITING_APPROVAL",
  AWAITING_FINAL_REVIEW: "AWAITING_FINAL_REVIEW",
  AWAITING_DELIVERY_SCHEDULE: "AWAITING_DELIVERY_SCHEDULE",
  EXECUTING: "EXECUTING",
  COMPLETED: "COMPLETED",
  ERROR: "ERROR",
};

const VALID_TRANSITIONS = {
  [WORKSPACE_STATES.IDLE]: [
    WORKSPACE_STATES.UNDERSTANDING,
    WORKSPACE_STATES.AWAITING_ENTITY,
    WORKSPACE_STATES.COLLECTING_INPUT,
    WORKSPACE_STATES.AWAITING_APPROVAL,
    WORKSPACE_STATES.AWAITING_FINAL_REVIEW,
    WORKSPACE_STATES.AWAITING_DELIVERY_SCHEDULE,
    WORKSPACE_STATES.EXECUTING,
    WORKSPACE_STATES.COMPLETED,
    WORKSPACE_STATES.ERROR,
  ],
  [WORKSPACE_STATES.UNDERSTANDING]: [
    WORKSPACE_STATES.AWAITING_ENTITY,
    WORKSPACE_STATES.COLLECTING_INPUT,
    WORKSPACE_STATES.AWAITING_APPROVAL,
    WORKSPACE_STATES.AWAITING_FINAL_REVIEW,
    WORKSPACE_STATES.AWAITING_DELIVERY_SCHEDULE,
    WORKSPACE_STATES.EXECUTING,
    WORKSPACE_STATES.COMPLETED,
    WORKSPACE_STATES.ERROR,
  ],
  [WORKSPACE_STATES.AWAITING_ENTITY]: [
    WORKSPACE_STATES.COLLECTING_INPUT,
    WORKSPACE_STATES.AWAITING_APPROVAL,
    WORKSPACE_STATES.AWAITING_FINAL_REVIEW,
    WORKSPACE_STATES.EXECUTING,
    WORKSPACE_STATES.COMPLETED,
    WORKSPACE_STATES.IDLE,
    WORKSPACE_STATES.ERROR,
  ],
  [WORKSPACE_STATES.COLLECTING_INPUT]: [
    WORKSPACE_STATES.COLLECTING_INPUT,
    WORKSPACE_STATES.AWAITING_APPROVAL,
    WORKSPACE_STATES.AWAITING_FINAL_REVIEW,
    WORKSPACE_STATES.EXECUTING,
    WORKSPACE_STATES.COMPLETED,
    WORKSPACE_STATES.IDLE,
    WORKSPACE_STATES.ERROR,
  ],
  [WORKSPACE_STATES.AWAITING_APPROVAL]: [
    WORKSPACE_STATES.AWAITING_FINAL_REVIEW,
    WORKSPACE_STATES.AWAITING_DELIVERY_SCHEDULE,
    WORKSPACE_STATES.EXECUTING,
    WORKSPACE_STATES.COMPLETED,
    WORKSPACE_STATES.COLLECTING_INPUT,
    WORKSPACE_STATES.IDLE,
    WORKSPACE_STATES.ERROR,
  ],
  [WORKSPACE_STATES.AWAITING_FINAL_REVIEW]: [
    WORKSPACE_STATES.AWAITING_DELIVERY_SCHEDULE,
    WORKSPACE_STATES.AWAITING_APPROVAL,
    WORKSPACE_STATES.EXECUTING,
    WORKSPACE_STATES.COMPLETED,
    WORKSPACE_STATES.IDLE,
    WORKSPACE_STATES.ERROR,
  ],
  [WORKSPACE_STATES.AWAITING_DELIVERY_SCHEDULE]: [
    WORKSPACE_STATES.COMPLETED,
    WORKSPACE_STATES.AWAITING_FINAL_REVIEW,
    WORKSPACE_STATES.EXECUTING,
    WORKSPACE_STATES.IDLE,
    WORKSPACE_STATES.ERROR,
  ],
  [WORKSPACE_STATES.EXECUTING]: [
    WORKSPACE_STATES.COMPLETED,
    WORKSPACE_STATES.AWAITING_APPROVAL,
    WORKSPACE_STATES.IDLE,
    WORKSPACE_STATES.ERROR,
  ],
  [WORKSPACE_STATES.COMPLETED]: [
    WORKSPACE_STATES.IDLE,
    WORKSPACE_STATES.UNDERSTANDING,
    WORKSPACE_STATES.AWAITING_ENTITY,
    WORKSPACE_STATES.COLLECTING_INPUT,
    WORKSPACE_STATES.AWAITING_APPROVAL,
    WORKSPACE_STATES.EXECUTING,
  ],
  [WORKSPACE_STATES.ERROR]: [
    WORKSPACE_STATES.IDLE,
    WORKSPACE_STATES.UNDERSTANDING,
    WORKSPACE_STATES.AWAITING_ENTITY,
    WORKSPACE_STATES.COLLECTING_INPUT,
    WORKSPACE_STATES.AWAITING_APPROVAL,
    WORKSPACE_STATES.EXECUTING,
  ],
};

function validateTransition(currentState, nextState) {
  const allowed = VALID_TRANSITIONS[currentState] || [];
  if (!allowed.includes(nextState)) {
    console.warn(`[StateMachine] Invalid state transition requested from ${currentState} to ${nextState}`);
    return false;
  }
  return true;
}

module.exports = {
  WORKSPACE_STATES,
  VALID_TRANSITIONS,
  validateTransition,
};
